### ISSUE TITLE
support r00

### ISSUE THREAD

**Issue by accessone67** [davidnewhall/deluge-unpacker#14]
Can you also add support for *.r00 files to extract

**Comment by davidnewhall** [comment]
Did you come across one that started with r00 and no rar? Haven't seen that yet. I can get fix it; give me a couple days.

**Comment by davidnewhall** [comment]
This is not as easy as it seems. 

For most archives, `.r00` is the second file where `.rar` is the first. I have not found an archive that was missing the `.rar` file and allows extraction starting from `.r00`. I'd really like to know what you found that starts with `.r00` - that throws off all my logic. hm.

**Comment by davidnewhall** [comment]
The latest release should fix this.

**Comment by Little709** [comment]
I just installed this and started using it. Everything checks out.

Deluge is detected
sonarr is detected
it even has a .rar file but the log says : (no extractable files found)

Might not be entirely this issue but hey. I thought i'd give it a go.

**Comment by davidnewhall** [comment]
hm. put it in debug mode, and see if anything more useful comes out of the logs? If there's a car file it usually finds it and extracts it, that's not an issue I've seen yet. Been running this app for a really long time too. :D

**Comment by Little709** [comment]
I put it in debug mode. but i doesn't output any thing that is of use really:

2020/02/09 19:55:33.646742 pollers.go:89: Extract Statuses: 0 extracting, 0 queued, 0 extracted, 0 imported, 0 failed, 0 deleted. Finished: 0

2020/02/09 19:55:33.653420 pollers.go:39: Sonarr Updated: 4 Items Queued
2020/02/09 19:55:33.693663 pollers.go:55: Radarr Updated: 1 Items Queued
2020/02/09 19:55:33.728090 pollers.go:23: Deluge Updated: 55 Transfers

2020/02/09 19:55:33.728139 pollers.go:227: [DEBUG] Sonarr: Completed Item still in Queue: *removed name* (no extractable files found)
2020/02/09 19:55:33.728140 pollers.go:227: [DEBUG] Sonarr: Completed Item still in Queue: *removed name* (no extractable files found)
2020/02/09 19:55:33.728153 pollers.go:227: [DEBUG] Sonarr: Completed Item still in Queue: *removed name* (no extractable files found)
2020/02/09 19:55:33.728161 pollers.go:227: [DEBUG] Radarr: Completed Item still in Queue: T-*removed name* (no extractable files found)
2020/02/09 19:55:33.728168 pollers.go:227: [DEBUG] Sonarr: Completed Item still in Queue: *removed name* (no extractable files found)

**Comment by davidnewhall** [comment]
okay so it doesn't find _any_ files. This tells me your `/downloads` folder is not mapped into this container at the correct path. The path for downloads must be the same on Deluge, Sonarr, Radarr and this app. If they differ, this app can't match the paths. I just use `/downloads` on all of them and it works well.

**Comment by davidnewhall** [comment]
I'm going to go ahead and close this out. If you're still having problems please open another Issue and provide the paths that your applications use for Downloads and paths you have mapped into your containers. Thanks!

**Comment by Irontoe** [comment]
I have the same issue:

Here are the debug file and yes, I did check that the /downloads folder is completely identical on Radarr/Sonarr/Unpackerr:

2020/04/23 02:13:04.532059 apps.go:71: [Radarr] Updated (http://192.168.1.232:7878/): 0 Items Queued
2020/04/23 02:13:04.532217 apps.go:51: [Sonarr] Updated (http://192.168.1.232:8989/): 1 Items Queued
2020/04/23 02:13:04.532371 handlers.go:76: [Sonarr] Completed item still waiting: _removed_, no extractable files found at: /Media/Complete/_removed_
2020/04/23 02:13:04.532418 apps.go:94: [DEBUG] Sonarr (http://192.168.1.232:8989/): Completed (torrent:100%): _removed_
2020/04/23 02:13:04.532457 pollers.go:121: [DEBUG] Sonarr: Status: _removed_ (Waiting, pre-Queue, elapsed: 5m0s, found: true)
2020/04/23 02:13:04.532500 logs.go:57: [Unpackerr] Queue: [1 waiting] [0 queued] [0 extracting] [0 extracted] [0 imported] [0 failed] [0 deleted], Totals: [0 restarts] [0 finished]

**Comment by davidnewhall** [comment]
@Irontoe Please open a new issue. Include:
- What file are in this path that should be extracted: `/Media/Complete/removed`
- How you run unpacker (docker/linux, etc)
- The Docker startup command.
- A screenshot of the error from Sonarr.
