### ISSUE TITLE
Radarr error while running the v3 preview - Docker unraid

### ISSUE THREAD

**Issue by MammothJerk** [davidnewhall/deluge-unpacker#18]
![](https://i.imgur.com/E6y10yo.png)

Running under the linuxserver/radarr:preview repo in unraid docker i'm getting this error in the log

`2020/02/08 11:45:34.832878 start.go:193: [ERROR] Radarr: json.Unmarshal(response): json: cannot unmarshal object into Go struct field .movie.alternativeTitles.language of type string`

not sure if this error is on your end or on the end of the v3 preview.

I got sonarr v3 preview running without this problem

**Comment by davidnewhall** [comment]
Grab the `master` tag.Does that work?

**Comment by davidnewhall** [comment]
eh, I don't think latest will fix this. hm. This is the second change v3 has brought; I already fixed one. This is interesting. Let me see if I can get something out soon!

**Comment by davidnewhall** [comment]
I just realized it's Radarr you're having a problem with not sonarr. Sonarr is the one I already fixed, but honestly I expect it to break again because I just slapped a bandaid on it and I think they're still changing things. I just installed the preview tag you mentioned and I'm checking this out now...

**Comment by davidnewhall** [comment]
I'm not in a good place to get things into Radarr, so I can't really see what the new API output looks like at the moment. I did make a change, another bandaid, that may resolve this. In about 20 minutes a new Docker image should finish building.

**Comment by MammothJerk** [comment]
Works great now, no issues with either sonarr v3 or radarr v3

**Comment by davidnewhall** [comment]
Sweet. I imagine things will change, please let me know! Thanks!

**Comment by MammothJerk** [comment]
will do!
