### ISSUE TITLE
what if i dont use Deluge?

### ISSUE THREAD

**Issue by Nach0-Stallion** [davidnewhall/deluge-unpacker#20]
Hi, i am an Unraid user and i just saw your app listed in the store section.

I have been looking for something to unpack my Sonarr and radarr download automatically ever since i moved from a windows system, however i dont use Deluge, is there a way for this app to just talk to sonarr/radarr looking for downloads and unpack them into the same folder as the .rar files (i have been doing that manually) and then sonarr/radarr will automatically process them (or if this app could ping them to force a check that would be cool too!)
but if its only for deluge then I understand :)

**Comment by davidnewhall** [comment]
You just gave me some good ideas for a future incarnation of this application. Unfortunately, right now, it requires Deluge.

**Comment by Nach0-Stallion** [comment]
Well please keep us posted should you either update this or release a seperate app, you could call it “Unpackerr”. Haha

**Comment by davidnewhall** [comment]
Dude! I like it.

**Comment by davidnewhall** [comment]
Just for fun, try this?

Grab the unraid template. Change the image location from `golift/deluge-unpacker` to `twitchcaptain/unpackerr`, remove the deluge settings (you have to turn on advanced), and add a single new variable named `DU_SAVE_PATH`. Set this to your mapped download location (ie. `/downloads`). 

I have no idea if this will work. It'll probably crash. hah

**Comment by davidnewhall** [comment]
Are you on discord? https://discord.gg/7NDSVg9

**Comment by davidnewhall** [comment]
So far this is working for me.
